//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryReptile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Lottery
    {
        public int ID { get; set; }
        public string LotteryName { get; set; }
        public int State { get; set; }
        public string Url1 { get; set; }
        public string Url2 { get; set; }
        public int IsUrl { get; set; }
    }
}
